#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SCLAlertView.Droid.Resource", IsApplication=false)]

namespace SCLAlertView.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int error_frame_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int error_x_in = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int modal_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int modal_out = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int success_bow_roate = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int success_mask_layout = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int fromDeg = 2130771969;
			
			// aapt resource value: 0x7f010003
			public static int pivotX = 2130771971;
			
			// aapt resource value: 0x7f010004
			public static int pivotY = 2130771972;
			
			// aapt resource value: 0x7f010000
			public static int rollType = 2130771968;
			
			// aapt resource value: 0x7f010002
			public static int toDeg = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050005
			public static int blue_btn_bg_color = 2131034117;
			
			// aapt resource value: 0x7f050006
			public static int blue_btn_bg_pressed_color = 2131034118;
			
			// aapt resource value: 0x7f050002
			public static int button_text_color = 2131034114;
			
			// aapt resource value: 0x7f050009
			public static int error_stroke_color = 2131034121;
			
			// aapt resource value: 0x7f050000
			public static int float_transparent = 2131034112;
			
			// aapt resource value: 0x7f050003
			public static int gray_btn_bg_color = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int gray_btn_bg_pressed_color = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public static int material_blue_grey_80 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public static int material_blue_grey_90 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public static int material_blue_grey_95 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public static int material_deep_teal_20 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public static int material_deep_teal_50 = 2131034130;
			
			// aapt resource value: 0x7f050007
			public static int red_btn_bg_color = 2131034119;
			
			// aapt resource value: 0x7f050008
			public static int red_btn_bg_pressed_color = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public static int success_stroke_color = 2131034122;
			
			// aapt resource value: 0x7f050001
			public static int sweet_dialog_bg_color = 2131034113;
			
			// aapt resource value: 0x7f05000d
			public static int text_color = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public static int trans_success_stroke_color = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public static int warning_stroke_color = 2131034124;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public static int alert_width = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int common_circle_width = 2131099649;
			
			// aapt resource value: 0x7f060002
			public static int progress_circle_radius = 2131099650;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int blue_button_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int dialog_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int error_center_x = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int error_circle = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int gray_button_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public static int red_button_background = 2130837509;
			
			// aapt resource value: 0x7f020006
			public static int success_bow = 2130837510;
			
			// aapt resource value: 0x7f020007
			public static int success_circle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public static int warning_circle = 2130837512;
			
			// aapt resource value: 0x7f020009
			public static int warning_sigh = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090010
			public static int cancel_button = 2131296272;
			
			// aapt resource value: 0x7f090011
			public static int confirm_button = 2131296273;
			
			// aapt resource value: 0x7f09000f
			public static int content_text = 2131296271;
			
			// aapt resource value: 0x7f090004
			public static int custom_image = 2131296260;
			
			// aapt resource value: 0x7f090005
			public static int error_frame = 2131296261;
			
			// aapt resource value: 0x7f090006
			public static int error_x = 2131296262;
			
			// aapt resource value: 0x7f090003
			public static int loading = 2131296259;
			
			// aapt resource value: 0x7f090009
			public static int mask_left = 2131296265;
			
			// aapt resource value: 0x7f090008
			public static int mask_right = 2131296264;
			
			// aapt resource value: 0x7f09000d
			public static int progressWheel = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public static int progress_dialog = 2131296268;
			
			// aapt resource value: 0x7f090007
			public static int success_frame = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public static int success_tick = 2131296266;
			
			// aapt resource value: 0x7f09000e
			public static int title_text = 2131296270;
			
			// aapt resource value: 0x7f09000b
			public static int warning_frame = 2131296267;
			
			// aapt resource value: 0x7f090000
			public static int x = 2131296256;
			
			// aapt resource value: 0x7f090001
			public static int y = 2131296257;
			
			// aapt resource value: 0x7f090002
			public static int z = 2131296258;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int alert_dialog = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070004
			public static int LOADING = 2131165188;
			
			// aapt resource value: 0x7f070000
			public static int app_name = 2131165184;
			
			// aapt resource value: 0x7f070003
			public static int dialog_cancel = 2131165187;
			
			// aapt resource value: 0x7f070001
			public static int dialog_default_title = 2131165185;
			
			// aapt resource value: 0x7f070002
			public static int dialog_ok = 2131165186;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public static int alert_dialog = 2131230720;
			
			// aapt resource value: 0x7f080001
			public static int dialog_blue_button = 2131230721;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] Rotate3dAnimation = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public static int Rotate3dAnimation_fromDeg = 1;
			
			// aapt resource value: 3
			public static int Rotate3dAnimation_pivotX = 3;
			
			// aapt resource value: 4
			public static int Rotate3dAnimation_pivotY = 4;
			
			// aapt resource value: 0
			public static int Rotate3dAnimation_rollType = 0;
			
			// aapt resource value: 2
			public static int Rotate3dAnimation_toDeg = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
